app/home/controllers.py
from flask import Blueprint, render_template
import json

mod_home = Blueprint('home', __name__, url_prefix='/')


@mod_home.route("/")
def home():
    with open(f"program/sinf1ba-an1.json") as file:
        data = json.load(file)

        return render_template("home/index.html", title="Home", data=data)

app/pae/controllers.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required
import json
from app.encodage.controllers import available_endpoints, program_json
from app.encodage.models import SucceededCourse
from . import SuggPAE

mod_pae = Blueprint('pae', __name__, url_prefix='/pae')

def flatten_course_dict(course_dict, sigle_to_remove):
    flat_course_dict = {}
    for category in course_dict:
        for course in course_dict[category]["course"]:
            if not course in sigle_to_remove:
                flat_course_dict[course] = course_dict[category]["course"][course]

    return flat_course_dict

def flat_and_merge_dict(program_json, sigle_to_remove):
    final_dict = {}
    for year in program_json:
        flat_dict = flatten_course_dict(program_json[year], sigle_to_remove)
        final_dict[year] = flat_dict
        
    return final_dict

def no_access(succeeded_course, course_list):
    no_prerequisite = []
    for year in course_list:
        for course in course_list[year]:
            if course_list[year][course].get("prerequisite"):
                prerequisite_pass = True
                for prerequisite in course_list[year][course].get("prerequisite"):
                    if not prerequisite in succeeded_course:
                        no_prerequisite.append(course)
                        break
    return no_prerequisite
                




@mod_pae.route("/")
@login_required
def pae():
    user_cts = SucceededCourse.build_user_cts_dict(current_user.username)
    succeeded_course = SucceededCourse.query.filter_by(username=current_user.username, other_out_program=False, other_minor=False).all()
    succeeded_list = list(map(lambda x: x.course_acronym, succeeded_course))
    data = flat_and_merge_dict(program_json, succeeded_list)

    succeeded_other_minor = SucceededCourse.query.filter_by(username=current_user.username, other_out_program=False, other_minor=True).filter('bloc' != "hors_programme").all()
    succeeded_other_minor_cts = sum(list(map(lambda x: x.cts, succeeded_other_minor)))
    #no_prerequisite = no_access(succeeded_course, data)
    suggestion, prog_cts, msg = SuggPAE.genSugg(succeeded_list, False, [[0,succeeded_other_minor_cts]])
    print(succeeded_list)
    print(succeeded_other_minor_cts)
    print(msg)
    msg = msg.split('\n')
    print(suggestion)
    
    return render_template("pae/index.html", title="Mon PAE", data=data, user_cts=user_cts, available_endpoints=available_endpoints, suggestion=suggestion, msg=msg)

app/templates/base.html
<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <link rel="stylesheet" href="{{ url_for('static', filename='encodage/boxed-check.min.css') }}">

    

    <title>PAE SINF - {{title}}</title>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">PAE SINF</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if not current_user.is_authenticated %}
            <a class="nav-link {% if title == "Home" %} active {% endif %}" aria-current="page" href={{ url_for('home.home') }}>Home</a>
            {% endif %}
            <a class="nav-link {% if title == "Mon parcours" %} active {% endif %}" href={{ url_for('encodage.bac', year="bac1") }}>Mon Parcours</a>
          </div>

          <ul class="navbar-nav ms-auto">
          {% if current_user.is_authenticated %}
            {% if current_user.is_admin %}
            <li class="nav-item">
              <a class="nav-link" href={{ url_for('admin.index') }}>Admin</a>
            </li>
            {%endif%}
          <li class="nav-item">
            <a class="nav-link" href={{ url_for('auth.logout') }}>Logout</a>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Se connecter</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.register') }}" >S'enregistrer</a>
            </li>
          {% endif %}
        </ul>
        </div>
      </div>
    </nav>



    <!-- NAVBAR
    <nav class="navbar navbar-dark navbar-expand-lg" style="background-color:#018BBA">
      <a class="navbar-brand" href="/">
        PAE SINF
      </a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav ml-auto">
          <li>
          <li class="nav-item active">
            <a class="nav-link" href={{ url_for('home.home') }}>Home <span class="sr-only">(current)</span></a>
          </li>

          {% if current_user.is_authenticated %}
            {% if current_user.is_admin %}
            <li class="nav-item">
              <a class="nav-link" href={{ url_for('admin.index') }}>Admin</a>
            </li>
            {%endif%}
          <li class="nav-item">
            <a class="nav-link" href={{ url_for('auth.logout') }}>Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href={{ url_for('auth.login') }}>Login</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href={{ url_for('auth.register') }}>Register</a>
          </li>

          {%endif%}
          </li>
        </ul>

      </div>
    </nav> -->
    <!-- END NAVBAR -->
 

    <div class="container-fluid">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }} mt-3">
              {{message}}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% block content %} {% endblock %}
    </div>
    <!-- END CONTAINER-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
			  src="https://code.jquery.com/jquery-3.6.0.min.js"
			  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			  crossorigin="anonymous"></script>
		
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
      crossorigin="anonymous"></script>

      
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='encodage/checked.js') }}"></script>
    <script src="{{ url_for('static', filename='encodage/dynamicTable.js') }}"></script>

  </body>

</html>

app/templates/dynamicTable.html
{% macro dynamicTable(prev_courses) -%}
<table id="minorTable" class="dynamicTable table order-list">
    <thead>
        <tr>
            <td>Sigle</td>
            <td>Titre</td>
            <td>Crédits</td>
        </tr>
    </thead>
    <tbody>
      {% if prev_courses %}
        {% for courses in prev_courses %}
        <tr>
            <td class="col-sm-4">
                <input type="text" minlength="9" maxlength="9" name="sigle{{loop.index-1}}" class="form-control" value="{{courses.course_acronym}}" />
            </td>
            <td class="col-sm-4">
                <input type="text" minlength="1" maxlength="150" name="titre{{loop.index-1}}"  class="form-control" value="{{courses.course_title}}"/>
            </td>
            <td class="col-sm-3">
                <input type="number" name="cts{{loop.index-1}}" min="1" max="15" class="form-control minorCts" value="{{courses.cts}}"/>
            </td>
            {% if loop.index > 1 %}
              <td><input type="button" class="ibtnDel btn btn-md btn-danger "  value="Delete"></td>
            {% endif %}
            <td class="col-sm-2"><a class="deleteRow"></a>

            </td>
        </tr>
        {% endfor %}
      {% else %}
        <tr>
          <td class="col-sm-4">
              <input type="text" minlength="9" maxlength="9" name="sigle0" class="form-control" />
          </td>
          <td class="col-sm-4">
              <input type="text" minlength="1" maxlength="150" name="titre0"  class="form-control"/>
          </td>
          <td class="col-sm-3">
              <input type="number" name="cts0" min="1" max="15" class="form-control minorCts" />
          </td>
          <td class="col-sm-2"><a class="deleteRow"></a>

          </td>
      </tr>
      {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5" style="text-align: center;">
                <input type="button" class="btn btn-lg btn-block " id="addrow" value="Ajouter un cours" />
            </td>
        </tr>
        <tr>
        </tr>
    </tfoot>
</table>
{%- endmacro %}

app/templates/sidebar.html
{% macro sidebar(year, available_endpoints, user_cts) -%}
<div class="col-md-3 order-md-2 mb-4">
      <div class="position-md-fixed">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                  <span class="text-muted">Cours crédités</span>
            </h4>
            <ul class="list-group mb-3">
                  {% for endpoint in available_endpoints %}
                  <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                              <div {% if year==endpoint %} class="text-success" {% endif %}>
                                    {% if year == endpoint %}
                                    <h6 class="my-0 text-success">{{endpoint}}</h6>
                                    {% else %}

                                    <h6 class="my-0">
                                          <h6 class="my-0"><a href="/encodage/{{endpoint}}"
                                                      class="link-dark">{{endpoint}}</a></h6>
                                          {% endif %}
                                          <small {% if year==endpoint %} class="text-success" {% endif %}>Cours crédités
                                                en {{endpoint}}</small>
                              </div>
                        </div>
                        {% if year == endpoint %}
                        <span class="text-success" id="{{endpoint}}">0</span>
                        {% else %}
                        <span id="{{endpoint}}">{{user_cts[endpoint]}}</span>
                        {% endif %}

                  </li>
                  {% endfor %}

                  <li class="list-group-item d-flex justify-content-between">
                        <span>Total</span>
                        <strong id="Total">0</strong>
                  </li>

                  <li class="list-group-item d-flex justify-center">
                        
                        {% if year %}
                        <button type="submit" form="courseForm" id="submitForm" class="btn btn-success">Je passe à la
                              prochaine étape</button>
                        {% else %}
                        <a href="{{url_for('pae.pae')}}" class="btn btn-success">Je confirme mon parcours et j'encode mon PAE</a>
                        {% endif%}
                  </li>
            </ul>
      </div>
</div>

{%- endmacro %}